In [74]:
import polars as pl

In [75]:
raw_y = pl.read_csv(rf'D:\wise\acct_RZ\data\demo\y.csv')
final = pl.read_parquet(rf'D:\wise\acct_RZ\data\result\blacklist_features.parquet')
blacklist = pl.read_parquet(rf'D:\wise\acct_RZ\data\result\step1_blacklist.parquet')
tracebCK = pl.read_parquet(rf'D:\wise\acct_RZ\data\result\step2_traceback.parquet')
org_bl = pl.read_parquet(rf'D:\wise\acct_RZ\data\result\step3_org_blacklist.parquet')
window_cnt = pl.read_parquet(rf'D:\wise\acct_RZ\data\result\step4_window_counts.parquet')

In [76]:
raw_y.filter(pl.col('PID')==10000279)

shape: (5, 13)
┌──────────┬─────┬──────────┬────────┬───┬──────────────┬─────────────┬─────────────┬──────────────┐
│ PID      ┆ ID  ┆ app_dt   ┆ target ┆ … ┆ observe_mont ┆ sample_flag ┆ channel_new ┆ ind          │
│ ---      ┆ --- ┆ ---      ┆ ---    ┆   ┆ h            ┆ ---         ┆ ---         ┆ ---          │
│ i64      ┆ i64 ┆ i64      ┆ i64    ┆   ┆ ---          ┆ str         ┆ str         ┆ str          │
│          ┆     ┆          ┆        ┆   ┆ i64          ┆             ┆             ┆              │
╞══════════╪═════╪══════════╪════════╪═══╪══════════════╪═════════════╪═════════════╪══════════════╡
│ 10000279 ┆ 837 ┆ 20251006 ┆ 0      ┆ … ┆ 3            ┆ mob3_dpd30  ┆ api         ┆ 拍拍贷#mob3_ │
│          ┆     ┆          ┆        ┆   ┆              ┆             ┆             ┆ dpd30#api    │
│ 10000279 ┆ 838 ┆ 20240717 ┆ 1      ┆ … ┆ 9            ┆ mob9_dpd60  ┆ api         ┆ 美团月付#mob │
│          ┆     ┆          ┆        ┆   ┆              ┆             ┆             ┆ 9_dpd60#api  │
│ 10000279 ┆ 839 ┆ 20240327 ┆ 1      ┆ … ┆ 12           ┆ mob12_dpd30 ┆ api         ┆ 零钱罐#mob12 │
│          ┆     ┆          ┆        ┆   ┆              ┆             ┆             ┆ _dpd30#api   │
│ 10000279 ┆ 839 ┆ 20240327 ┆ 1      ┆ … ┆ 3            ┆ mob3_dpd60  ┆ 小程序      ┆ 分期乐#mob3_ │
│          ┆     ┆          ┆        ┆   ┆              ┆             ┆             ┆ dpd60#小程序 │
│ 10000279 ┆ 839 ┆ 20240327 ┆ 0      ┆ … ┆ null         ┆ fpd30       ┆ 小程序      ┆ 零钱罐#fpd30 │
│          ┆     ┆          ┆        ┆   ┆              ┆             ┆             ┆ #小程序      │
└──────────┴─────┴──────────┴────────┴───┴──────────────┴─────────────┴─────────────┴──────────────┘

In [77]:
final

shape: (1, 121)
┌────────────┬──────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ app_dt     ┆ key_type ┆ key_value ┆ PID      ┆ … ┆ is_multi_ ┆ is_multi_ ┆ latest_de ┆ latest_de │
│ ---        ┆ ---      ┆ ---       ┆ ---      ┆   ┆ perf_defa ┆ perf_defa ┆ fault_org ┆ fault_per │
│ date       ┆ str      ┆ str       ┆ str      ┆   ┆ ult_24m   ┆ ult_36m   ┆ _type     ┆ f_type    │
│            ┆          ┆           ┆          ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆          ┆           ┆          ┆   ┆ i8        ┆ i8        ┆ str       ┆ str       │
╞════════════╪══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2025-10-06 ┆ pid      ┆ 10000279  ┆ 10000279 ┆ … ┆ 0         ┆ 0         ┆ null      ┆ null      │
└────────────┴──────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [61]:
tracebCK#.sort('hit_event_cnt_asof_dt',descending=True)

shape: (1, 9)
┌──────────┬──────────┬───────────┬─────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ app_dt   ┆ key_type ┆ key_value ┆ PID ┆ … ┆ black_hit_e ┆ first_defau ┆ latest_defa ┆ hit_event_ │
│ ---      ┆ ---      ┆ ---       ┆ --- ┆   ┆ ver         ┆ lt_event_dt ┆ ult_event_d ┆ cnt_asof_d │
│ i64      ┆ str      ┆ str       ┆ str ┆   ┆ ---         ┆ ---         ┆ t           ┆ t          │
│          ┆          ┆           ┆     ┆   ┆ i8          ┆ i64         ┆ ---         ┆ ---        │
│          ┆          ┆           ┆     ┆   ┆             ┆             ┆ i64         ┆ u32        │
╞══════════╪══════════╪═══════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 20251006 ┆ pid      ┆ p1        ┆ p1  ┆ … ┆ 0           ┆ null        ┆ null        ┆ 0          │
└──────────┴──────────┴───────────┴─────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [62]:
org_bl

shape: (3, 8)
┌──────────┬──────────┬───────────┬─────┬──────┬───────────┬───────────────────┬───────────────────┐
│ app_dt   ┆ key_type ┆ key_value ┆ PID ┆ ID   ┆ org_class ┆ black_hit_ever_by ┆ first_default_eve │
│ ---      ┆ ---      ┆ ---       ┆ --- ┆ ---  ┆ ---       ┆ _org_class        ┆ nt_dt_by_org_…    │
│ i64      ┆ str      ┆ str       ┆ str ┆ str  ┆ str       ┆ ---               ┆ ---               │
│          ┆          ┆           ┆     ┆      ┆           ┆ i8                ┆ i64               │
╞══════════╪══════════╪═══════════╪═════╪══════╪═══════════╪═══════════════════╪═══════════════════╡
│ 20251006 ┆ pid      ┆ p1        ┆ p1  ┆ null ┆ Bank      ┆ 0                 ┆ null              │
│ 20251006 ┆ pid      ┆ p1        ┆ p1  ┆ null ┆ Rate24    ┆ 0                 ┆ null              │
│ 20251006 ┆ pid      ┆ p1        ┆ p1  ┆ null ┆ Rate36    ┆ 0                 ┆ null              │
└──────────┴──────────┴───────────┴─────┴──────┴───────────┴───────────────────┴───────────────────┘

In [55]:
window_cnt

shape: (2, 13)
┌──────────┬──────────┬───────────┬──────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ app_dt   ┆ key_type ┆ key_value ┆ PID      ┆ … ┆ default_cn ┆ default_cn ┆ default_c ┆ default_c │
│ ---      ┆ ---      ┆ ---       ┆ ---      ┆   ┆ t_6m_bank  ┆ t_3m_rate2 ┆ nt_3m_fpd ┆ nt_3m_dpd │
│ i64      ┆ str      ┆ str       ┆ str      ┆   ┆ ---        ┆ 4          ┆ ---       ┆ ---       │
│          ┆          ┆           ┆          ┆   ┆ u32        ┆ ---        ┆ u32       ┆ u32       │
│          ┆          ┆           ┆          ┆   ┆            ┆ u32        ┆           ┆           │
╞══════════╪══════════╪═══════════╪══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 20250417 ┆ pid      ┆ 10000279  ┆ 10000279 ┆ … ┆ 0          ┆ 1          ┆ 0         ┆ 2         │
│ 20251006 ┆ pid      ┆ 10000279  ┆ 10000279 ┆ … ┆ 0          ┆ 0          ┆ 0         ┆ 0         │
└──────────┴──────────┴───────────┴──────────┴───┴────────────┴────────────┴───────────┴───────────┘